language: node_js

node_js:
  - "7"

addons:
  rethinkdb: "2.3"

services:
  - redis

sudo: false

before_install:
  - printf "//registry.npmjs.org/:_authToken=${NPM_TOKEN}\n" >> .npmrc

cache:
  directories:
    - node_modules
